is.num = (n) => typeof n === "number" && !Number.isNaN(n);
is.isnan = (n) => Number.isNaN(n);
is.isstr = (n) => typeof n === "string";
is.bool = (n) => typeof n === "boolean";
is.undef = (n) => typeof n === "undefined";
is.def = (n) => typeof n !== "undefined";
is.arr = (n) => Array.isArray(n);
is.obj = (n) => typeof n === "object" && n != null && !is.arr(n);
is.fun = (n) => typeof n === "function";
is.truthy = (n) => !!n;
is.falsy = (n) => !n;
